name: weather
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  device_info: ^0.4.2+4
  flutter_device_type: ^0.2.0
  flutter_bloc: ^6.0.1
  rxdart: 0.24.1
  provider: ^4.3.1
  day_night_switch: ^0.0.2+1
  shared_preferences: ^0.5.8
  permission_handler: ^5.0.1+1
  flutter_launcher_icons: ^0.7.3
  flutter_icons: ^1.1.0
  font_awesome_flutter: ^8.11.0
  path: ^1.7.0
  path_provider_ex: ^1.0.1

  hive:
  hive_flutter:
    git:
      url: git://github.com/hivedb/hive.git
      path: hive_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
    git:
      url: git://github.com/hivedb/hive.git
      path: hive_generator
  build_runner: ^1.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_launcher/launcher.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Hero
      fonts:
        - asset: assets/fonts/HeroLight-Light.otf
          weight: 300
        - asset: assets/fonts/HeroLight-Regular.otf
          weight: 500
        - asset: assets/fonts/HeroLight-Bold.otf
          weight: 700

    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
  assets:
    - assets/images/cloud_afternoon.png
    - assets/images/cloud_evening.png
    - assets/images/cloud_morning.png
    - assets/images/cloud_night.png
    - assets/images/moon_afternoon.png
    - assets/images/moon_evening.png
    - assets/images/moon_morning.png
    - assets/images/moon_night.png
    - assets/images/rain_afternoon.png
    - assets/images/rain_evening.png
    - assets/images/rain_morning.png
    - assets/images/rain_night.png
    - assets/images/showers_afternoon.png
    - assets/images/showers_evening.png
    - assets/images/showers_morning.png
    - assets/images/showers_night.png
    - assets/images/snow_afternoon.png
    - assets/images/snow_evening.png
    - assets/images/snow_morning.png
    - assets/images/snow_night.png
    - assets/images/sunny_afternoon.png
    - assets/images/sunny_evening.png
    - assets/images/sunny_morning.png
    - assets/images/sunny_night.png
    - assets/images/hazy.png
    - assets/images/thunder_storm.png
    - assets/images/ice.png
    - assets/images/windy_afternoon.png
    - assets/images/windy_evening.png
    - assets/images/windy_morning.png
    - assets/images/windy_night.png
